### ISSUE TITLE
是否测试过bot代码运行

### ISSUE THREAD

**Issue by hongk-bb** [aaaatopos/Gobang#1]
我发现一个错误, 在bot代码服务中, 你的util包居然在service包下, 而你的consume查找的类名确实与service同级的目录, 你是否只是改写y的代码, 并没有测试这一块?

**Comment by aaaatopos** [comment]
我这个还没完成，还有点问题，我之前测试，Bot代码好像可以执行啊

>

**Comment by aaaatopos** [comment]
我这个还有问题，还没完全实现，但是我之前测试Bot代码是可以执行的啊

**Comment by hongk-bb** [comment]
我全帮你实现好了
